name: flutter_application_kcalnutritionapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  introduction_screen: ^2.1.0

  scroll_bottom_navigation_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.2.8

flutter_native_splash:
  color: "#ffffff"
  image: assets/landingpage_background.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/landingpage_background.png
    - assets/onBoard1.png
    - assets/onBoard2.png
    - assets/onBoard3.png
    - assets/rightArrow.png
    - assets/cookies.png
    - assets/gallery.jpg
    - assets/gallery2.jpg
    - assets/5-stars.png
    - assets/recipe1.jpg
    - assets/cabbage.jpg
    - assets/salmon.jpg
    - assets/lemon.jpg
    - assets/redchilli.jpg

  fonts:
    - family: rounded
      fonts:
        - asset: fonts/Simply-Rounded.ttf
    - family: rounded(2)
      fonts:
        - asset: fonts/Nunito-Bold.ttf
    - family: Barlow
      fonts:
        - asset: fonts/BarlowSemiCondensed-Light.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
